name: zgh
description: A geohash compression tool.
version: 0.0.1
homepage: 'https://github.com/ziggapp/zgh'

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.15.7
  proximity_hash: ^1.0.2
